"""Create appointments table

Revision ID: fae4204f4562
Revises: 
Create Date: 2026-06-14 22:28:45.686617

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fae4204f4562'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('appointment_time', sa.DateTime(), nullable=False),
    sa.Column('notification_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('users_userprofile')
    with op.batch_alter_table('users_customuser_user_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('users_customuser_user_permissions_customuser_id_5771478b'))
        batch_op.drop_index(batch_op.f('users_customuser_user_permissions_permission_id_baaa2f74'))

    op.drop_table('users_customuser_user_permissions')
    op.drop_table('course_courseorder')
    with op.batch_alter_table('users_customuser_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('users_customuser_groups_customuser_id_958147bf'))
        batch_op.drop_index(batch_op.f('users_customuser_groups_group_id_01390b14'))

    op.drop_table('users_customuser_groups')
    with op.batch_alter_table('auth_group_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('auth_group_permissions_group_id_b120cbf9'))
        batch_op.drop_index(batch_op.f('auth_group_permissions_permission_id_84c5c92e'))

    op.drop_table('auth_group_permissions')
    with op.batch_alter_table('users_workexperience', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('users_workexperience_user_profile_id_5446120b'))

    op.drop_table('users_workexperience')
    op.drop_table('django_migrations')
    with op.batch_alter_table('users_profilesharelink', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('users_profi_expiry__ba3c26_idx'))
        batch_op.drop_index(batch_op.f('users_profi_token_f228bf_idx'))
        batch_op.drop_index(batch_op.f('users_profilesharelink_user_id_1e7b4928'))

    op.drop_table('users_profilesharelink')
    with op.batch_alter_table('users_customuser', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('users_customuser_email_6445acef_like'), postgresql_ops={'email': 'varchar_pattern_ops'})
        batch_op.drop_index(batch_op.f('users_customuser_membership_id_2199a54e_like'), postgresql_ops={'membership_id': 'varchar_pattern_ops'})

    op.drop_table('users_customuser')
    op.drop_table('django_content_type')
    with op.batch_alter_table('users_profileviewlog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('users_profi_share_l_ee2e44_idx'))
        batch_op.drop_index(batch_op.f('users_profi_viewed__c7802f_idx'))
        batch_op.drop_index(batch_op.f('users_profileviewlog_share_link_id_93c0d773'))

    op.drop_table('users_profileviewlog')
    with op.batch_alter_table('django_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('django_session_expire_date_a5c62663'))
        batch_op.drop_index(batch_op.f('django_session_session_key_c0390e0f_like'), postgresql_ops={'session_key': 'varchar_pattern_ops'})

    op.drop_table('django_session')
    with op.batch_alter_table('auth_group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('auth_group_name_a6ea08ec_like'), postgresql_ops={'name': 'varchar_pattern_ops'})

    op.drop_table('auth_group')
    with op.batch_alter_table('users_education', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('users_education_user_profile_id_2e8a5ad9'))

    op.drop_table('users_education')
    with op.batch_alter_table('django_admin_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('django_admin_log_content_type_id_c4bce8eb'))
        batch_op.drop_index(batch_op.f('django_admin_log_user_id_c564eba6'))

    op.drop_table('django_admin_log')
    with op.batch_alter_table('auth_permission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('auth_permission_content_type_id_2f476e4b'))

    op.drop_table('auth_permission')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_permission',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('codename', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name=op.f('auth_permission_content_type_id_2f476e4b_fk_django_co'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('auth_permission_pkey')),
    sa.UniqueConstraint('content_type_id', 'codename', name=op.f('auth_permission_content_type_id_codename_01ab375a_uniq'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('auth_permission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('auth_permission_content_type_id_2f476e4b'), ['content_type_id'], unique=False)

    op.create_table('django_admin_log',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('action_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('object_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('object_repr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('action_flag', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('change_message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.CheckConstraint('action_flag >= 0', name=op.f('django_admin_log_action_flag_check')),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name=op.f('django_admin_log_content_type_id_c4bce8eb_fk_django_co'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users_customuser.id'], name=op.f('django_admin_log_user_id_c564eba6_fk_users_customuser_id'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('django_admin_log_pkey'))
    )
    with op.batch_alter_table('django_admin_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('django_admin_log_user_id_c564eba6'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('django_admin_log_content_type_id_c4bce8eb'), ['content_type_id'], unique=False)

    op.create_table('users_education',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('degree', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('university', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('year_of_completion', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('marks_cgpa', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('user_profile_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_profile_id'], ['users_userprofile.id'], name=op.f('users_education_user_profile_id_2e8a5ad9_fk_users_use'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_education_pkey'))
    )
    with op.batch_alter_table('users_education', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('users_education_user_profile_id_2e8a5ad9'), ['user_profile_id'], unique=False)

    op.create_table('auth_group',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('auth_group_pkey')),
    sa.UniqueConstraint('name', name=op.f('auth_group_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('auth_group', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('auth_group_name_a6ea08ec_like'), ['name'], unique=False, postgresql_ops={'name': 'varchar_pattern_ops'})

    op.create_table('django_session',
    sa.Column('session_key', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('session_data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expire_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('session_key', name=op.f('django_session_pkey'))
    )
    with op.batch_alter_table('django_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('django_session_session_key_c0390e0f_like'), ['session_key'], unique=False, postgresql_ops={'session_key': 'varchar_pattern_ops'})
        batch_op.create_index(batch_op.f('django_session_expire_date_a5c62663'), ['expire_date'], unique=False)

    op.create_table('users_profileviewlog',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('viewer_ip', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('viewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('share_link_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['share_link_id'], ['users_profilesharelink.id'], name=op.f('users_profileviewlog_share_link_id_93c0d773_fk_users_pro'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_profileviewlog_pkey'))
    )
    with op.batch_alter_table('users_profileviewlog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('users_profileviewlog_share_link_id_93c0d773'), ['share_link_id'], unique=False)
        batch_op.create_index(batch_op.f('users_profi_viewed__c7802f_idx'), ['viewed_at'], unique=False)
        batch_op.create_index(batch_op.f('users_profi_share_l_ee2e44_idx'), ['share_link_id'], unique=False)

    op.create_table('django_content_type',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('app_label', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('django_content_type_pkey')),
    sa.UniqueConstraint('app_label', 'model', name=op.f('django_content_type_app_label_model_76bd3d3b_uniq'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('users_customuser',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('last_login', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=254), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('profile_photo', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('resume', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('membership_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_staff', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_blocked', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_customuser_pkey')),
    sa.UniqueConstraint('email', name=op.f('users_customuser_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('membership_id', name=op.f('users_customuser_membership_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('users_customuser', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('users_customuser_membership_id_2199a54e_like'), ['membership_id'], unique=False, postgresql_ops={'membership_id': 'varchar_pattern_ops'})
        batch_op.create_index(batch_op.f('users_customuser_email_6445acef_like'), ['email'], unique=False, postgresql_ops={'email': 'varchar_pattern_ops'})

    op.create_table('users_profilesharelink',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('token', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('expiry_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users_customuser.id'], name=op.f('users_profilesharelink_user_id_1e7b4928_fk_users_customuser_id'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_profilesharelink_pkey')),
    sa.UniqueConstraint('token', name=op.f('users_profilesharelink_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('users_profilesharelink', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('users_profilesharelink_user_id_1e7b4928'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('users_profi_token_f228bf_idx'), ['token'], unique=False)
        batch_op.create_index(batch_op.f('users_profi_expiry__ba3c26_idx'), ['expiry_date'], unique=False)

    op.create_table('django_migrations',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('app', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('applied', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('django_migrations_pkey'))
    )
    op.create_table('users_workexperience',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('designation', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('responsibilities', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_profile_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_profile_id'], ['users_userprofile.id'], name=op.f('users_workexperience_user_profile_id_5446120b_fk_users_use'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_workexperience_pkey'))
    )
    with op.batch_alter_table('users_workexperience', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('users_workexperience_user_profile_id_5446120b'), ['user_profile_id'], unique=False)

    op.create_table('auth_group_permissions',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name=op.f('auth_group_permissions_group_id_b120cbf9_fk_auth_group_id'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name=op.f('auth_group_permissio_permission_id_84c5c92e_fk_auth_perm'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('auth_group_permissions_pkey')),
    sa.UniqueConstraint('group_id', 'permission_id', name=op.f('auth_group_permissions_group_id_permission_id_0cd325b0_uniq'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('auth_group_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('auth_group_permissions_permission_id_84c5c92e'), ['permission_id'], unique=False)
        batch_op.create_index(batch_op.f('auth_group_permissions_group_id_b120cbf9'), ['group_id'], unique=False)

    op.create_table('users_customuser_groups',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('customuser_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customuser_id'], ['users_customuser.id'], name=op.f('users_customuser_gro_customuser_id_958147bf_fk_users_cus'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name=op.f('users_customuser_groups_group_id_01390b14_fk_auth_group_id'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_customuser_groups_pkey')),
    sa.UniqueConstraint('customuser_id', 'group_id', name=op.f('users_customuser_groups_customuser_id_group_id_76b619e3_uniq'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('users_customuser_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('users_customuser_groups_group_id_01390b14'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('users_customuser_groups_customuser_id_958147bf'), ['customuser_id'], unique=False)

    op.create_table('course_courseorder',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('course_title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('razorpay_order_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('razorpay_payment_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('razorpay_signature', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('paid', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('course_courseorder_pkey'))
    )
    op.create_table('users_customuser_user_permissions',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('customuser_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customuser_id'], ['users_customuser.id'], name=op.f('users_customuser_use_customuser_id_5771478b_fk_users_cus'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name=op.f('users_customuser_use_permission_id_baaa2f74_fk_auth_perm'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_customuser_user_permissions_pkey')),
    sa.UniqueConstraint('customuser_id', 'permission_id', name=op.f('users_customuser_user_pe_customuser_id_permission_7a7debf6_uniq'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('users_customuser_user_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('users_customuser_user_permissions_permission_id_baaa2f74'), ['permission_id'], unique=False)
        batch_op.create_index(batch_op.f('users_customuser_user_permissions_customuser_id_5771478b'), ['customuser_id'], unique=False)

    op.create_table('users_userprofile',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('dob', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('contact', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('profile_photo', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('skills', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('languages', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('resume', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users_customuser.id'], name=op.f('users_userprofile_user_id_87251ef1_fk_users_customuser_id'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_userprofile_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('users_userprofile_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('appointments')
    # ### end Alembic commands ###
